spring:
  datasource:
    url: ${vcap.services.cleardb[0].credentials.jdbcUrl}
    username:  ${vcap.services.cleardb[0].credentials.username}
    password:  ${vcap.services.cleardb[0].credentials.password}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create