spring:  
  application:
    name: sathish-booking-service-mvc 

logging:
  level: DEBUG
    
  
# turn off the security on the actuator end points as this is a demo app
security:
  basic:
    enabled: false    

#booking-service-dao:
  #url: https://sathish-booking-service-dao.cfapps.io
